version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ${APPLICATION}:/var/www

### Workspace Utilities Container ###########################
    workspace:
      build:
        context: ./workspace
        args:
          - PUID=1000
          - PGID=1000
        dockerfile: "Dockerfile"
      volumes_from:
        - applications
      expose:
        - "4200"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      ports:
        - "22:22"
        - "4200:4200"
      tty: true
      networks:
        - frontend
        - backend
    jenkins:
        #image: wilbertjoosen/php_hemovida_jenkins:latest
        build:
            context: jenkins
            dockerfile: "Dockerfile"
        container_name: jenkins
        ports:
          - '8080:8080'
          - '8443:8443'
        volumes:
          - ./data/jenkins_2:/var/jenkins_home
        networks:
          - app  
        extra_hosts:
          - "hemovida.local.saude.gov.br:172.19.0.6"
          - "hemovida.desenvolvimento.saude.gov:10.1.1.144"

### PHP-FPM Container #######################################
    php:
      build:
        context: php
        dockerfile: "Dockerfile"
      volumes_from:
        - applications
      expose:
        - "9000"
        - "4200"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - XDEBUG_CONFIG= "remotehost=10.0.75.1"
      networks:
        - backend
        - frontend

### Apache Server Container #################################

    apache:
      build:
        context: ./apache
        args:
          - PHP_SOCKET=php:9000
      volumes_from:
        - applications
      volumes:
        - ./data/apache/logs:/var/log/apache2
        - ./data/apache/sites:/etc/apache2/sites-available
      ports:
        - "80:80"
      depends_on:
        - php
      links:
        - "php"
      networks:
        - frontend
        - backend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################
